=== itzfoxbrz/KamikaZL2/gametest/data/scripts/events/BlackCoupon/eventDetails.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list" type="listType"/>
	<xs:complexType name="configurationsType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:int" name="multisellID"/>
				<xs:attribute type="xs:string" name="showItemsInRange"/>
				<xs:attribute type="xs:int" name="couponID"/>
				<xs:attribute type="xs:int" name="couponCount"/>
				<xs:attribute type="xs:string" name="parseExchangeItemsBelow"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="itemType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:int" name="breakID" use="optional"/>
				<xs:attribute type="xs:int" name="restoreID" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="itemsType">
		<xs:sequence>
			<xs:element type="itemType" name="item" maxOccurs="unbounded" minOccurs="0" />
		</xs:sequence>
		<xs:attribute type="xs:string" name="category" use="optional"/>
	</xs:complexType>
	<xs:complexType name="exchangeType">
		<xs:sequence>
			<xs:element type="itemsType" name="items" maxOccurs="unbounded" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="listType">
		<xs:sequence>
			<xs:element type="configurationsType" name="configurations"/>
			<xs:element type="exchangeType" name="exchange"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== itzfoxbrz/KamikaZL2/gametest/source/L2J_Mobius_Essence_7.3_SevenSigns/dist/game/data/scripts/events/BlackCoupon/eventDetails.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="eventDetails.xsd">
	<!-- showInRange time in UNIX format -->
	<!-- showInRange time in UNIX coupon id - black coupon id -->
	<configurations multisellID="3247899" showItemsInRange="1651134344000;2524608000000" couponID="98022" couponCount="1" parseExchangeItemsBelow="true" />
	<exchange>
		<items category="WEAPON">
			<!-- BOSS WEAPON -->
			<item breakID="92404" restoreID="93291" /> <!-- Zaken's Blood Sword -->
			<item breakID="92405" restoreID="93292" /> <!-- Core's Plasmic Bow -->
			<item breakID="92407" restoreID="93293" /> <!-- Orfen's Venom Sword -->
			<item breakID="92408" restoreID="93294" /> <!-- Baium's Thunder Breaker -->
			<item breakID="92421" restoreID="93295" /> <!-- Queen Ant's Stone Breaker -->
			<item breakID="94888" restoreID="95422" /> <!-- Anakim's Divine Pistols -->
			<item breakID="96268" restoreID="96269" /> <!-- Beleth' Soul Eater -->
			<!-- Duplication for sealed items -->
			<item breakID="93291" /> <!-- Zaken's Blood Sword -->
			<item breakID="93292" /> <!-- Core's Plasmic Bow -->
			<item breakID="93293" /> <!-- Orfen's Venom Sword -->
			<item breakID="93294" /> <!-- Baium's Thunder Breaker -->
			<item breakID="93295" /> <!-- Queen Ant's Stone Breaker -->
			<item breakID="95422" /> <!-- Anakim's Divine Pistols -->
			<item breakID="96269" /> <!-- Beleth' Soul Eater -->
			<!-- Frost Lord Weapon -->
			<item breakID="95731" restoreID="96757" /> <!-- Frost Lord's Blade Fists -->
			<item breakID="95728" restoreID="96754" /> <!-- Frost Lord's Dagger -->
			<item breakID="95726" restoreID="96752" /> <!-- Frost Lord's Two-handed Sword -->
			<item breakID="95737" restoreID="96763" /> <!-- Frost Lord's Dual Swords -->
			<item breakID="95734" restoreID="96760" /> <!-- Frost Lord's Ancient Sword -->
			<item breakID="95733" restoreID="96759" /> <!-- Frost Lord's Staff -->
			<item breakID="95735" restoreID="96761" /> <!-- Frost Lord's Rapier -->
			<item breakID="95725" restoreID="96751" /> <!-- Frost Lord's Sword -->
			<item breakID="95730" restoreID="96756" /> <!-- Frost Lord's Bow -->
			<item breakID="95732" restoreID="96758" /> <!-- Frost Lord's Magic Blunt Weapon -->
			<item breakID="95736" restoreID="96762" /> <!-- Frost Lord's Pistols -->
			<item breakID="95727" restoreID="96753" /> <!-- Frost Lord's Axe -->
			<item breakID="95729" restoreID="96755" /> <!-- Frost Lord's Spear -->
			<!-- Duplication for sealed items -->
			<item breakID="96757" /> <!-- Frost Lord's Blade Fists -->
			<item breakID="96754" /> <!-- Frost Lord's Dagger -->
			<item breakID="96752" /> <!-- Frost Lord's Two-handed Sword -->
			<item breakID="96763" /> <!-- Frost Lord's Dual Swords -->
			<item breakID="96760" /> <!-- Frost Lord's Ancient Sword -->
			<item breakID="96759" /> <!-- Frost Lord's Staff -->
			<item breakID="96761" /> <!-- Frost Lord's Rapier -->
			<item breakID="96751" /> <!-- Frost Lord's Sword -->
			<item breakID="96756" /> <!-- Frost Lord's Bow -->
			<item breakID="96758" /> <!-- Frost Lord's Magic Blunt Weapon -->
			<item breakID="96762" /> <!-- Frost Lord's Pistols -->
			<item breakID="96753" /> <!-- Frost Lord's Axe -->
			<item breakID="96755" /> <!-- Frost Lord's Spear -->
			<!-- B GRADE -->
			<!-- Two-handed Blunts -->
			<item breakID="7900" restoreID="95311" /> <!-- Ice Storm Hammer -->
			<item breakID="7901" restoreID="93433" /> <!-- Star Buster -->
			<item breakID="95437" restoreID="95451" /> <!-- Sealed Angel's Hammer -->
			<!-- Duplication for sealed items -->
			<item breakID="95311" /> <!-- Ice Storm Hammer -->
			<item breakID="93433" /> <!-- Star Buster -->
			<item breakID="95451" /> <!-- Sealed Angel's Hammer -->
			<!-- Two-handed Swords -->
			<item breakID="78" restoreID="94918" /> <!-- Great Sword -->
			<item breakID="7883" restoreID="93431" /> <!-- Guardian's Sword -->
			<item breakID="95445" restoreID="95459" /> <!-- Butcher's Long Sword -->
			<!-- Duplication for sealed items -->
			<item breakID="94918" /> <!-- Great Sword -->
			<item breakID="93431" /> <!-- Guardian's Sword -->
			<item breakID="95459" /> <!-- Butcher's Long Sword -->
			<!-- Two-handed Staffs -->
			<item breakID="92" restoreID="94926" /> <!-- Spirit's Staff -->
			<item breakID="210" restoreID="93426" /> <!-- Staff of Evil Spirits -->
			<item breakID="95438" restoreID="95452" /> <!-- Lizardman Shaman's Staff -->
			<item breakID="96721" restoreID="96723" /> <!-- Giant's Two-handed Staff -->
			<!-- Duplication for sealed items -->
			<item breakID="94926" /> <!-- Spirit's Staff -->
			<item breakID="93426" /> <!-- Staff of Evil Spirits -->
			<item breakID="95452" /> <!-- Lizardman Shaman's Staff -->
			<item breakID="96723" /> <!-- Giant's Two-handed Staff -->
			<!-- Ancient Sword -->
			<item breakID="91885" restoreID="93434" /> <!-- Dismantler -->
			<item breakID="91886" restoreID="95318" /> <!-- Innominate Victory -->
			<item breakID="95441" restoreID="95455" /> <!-- Dragon Bone Blade -->
			<!-- Duplication for sealed items -->
			<item breakID="93434" /> <!-- Dismantler -->
			<item breakID="95318" /> <!-- Innominate Victory -->
			<item breakID="95455" /> <!-- Dragon Bone Blade -->
			<!-- Fist Weapon -->
			<item breakID="264" restoreID="95019" /> <!-- Pata -->
			<item breakID="267" restoreID="95021" /> <!-- Arthro Claw -->
			<item breakID="268" restoreID="93428" /> <!-- Bellion Cestus -->
			<item breakID="95433" restoreID="95447" /> <!-- Torfe's Claw -->
			<!-- Duplication for sealed items -->
			<item breakID="95019" /> <!-- Pata -->
			<item breakID="95021" /> <!-- Arthro Claw -->
			<item breakID="93428" /> <!-- Bellion Cestus -->
			<item breakID="95447" /> <!-- Torfe's Claw -->
			<!-- Daggers -->
			<item breakID="229" restoreID="95002" /> <!-- Kris -->
			<item breakID="234" restoreID="93427" /> <!-- Demon's Dagger -->
			<item breakID="243" restoreID="95012" /> <!-- Twilight Knife -->
			<item breakID="95440" restoreID="95454" /> <!-- Deadman's Dagger -->
			<!-- Duplication for sealed items -->
			<item breakID="95002" /> <!-- Kris -->
			<item breakID="93427" /> <!-- Demon's Dagger -->
			<item breakID="95012" /> <!-- Twilight Knife -->
			<item breakID="95454" /> <!-- Deadman's Dagger -->
			<!-- Polearms -->
			<item breakID="97" restoreID="93423" /> <!-- Lance -->
			<item breakID="300" restoreID="95042" /> <!-- Great Axe -->
			<item breakID="95436" restoreID="95450" /> <!-- Guardian Messenger's Spear -->
			<item breakID="97236" restoreID="97237" /> <!-- Spear of Xilenos -->
			<!-- Duplication for sealed items -->
			<item breakID="93423" /> <!-- Lance -->
			<item breakID="95042" /> <!-- Great Axe -->
			<item breakID="95450" /> <!-- Guardian Messenger's Spear -->
			<item breakID="97237" /> <!-- Spear of Xilenos -->
			<!-- Bows -->
			<item breakID="287" restoreID="93429" /> <!-- Bow of Peril -->
			<item breakID="284" restoreID="95032" /> <!-- Dark Elven Longbow -->
			<item breakID="95443" restoreID="95457" /> <!-- Sel Mahum Sniper -->
			<!-- Duplication for sealed items -->
			<item breakID="93429" /> <!-- Bow of Peril -->
			<item breakID="95032" /> <!-- Dark Elven Longbow -->
			<item breakID="95457" /> <!-- Sel Mahum Sniper -->
			<!-- Magic Swords -->
			<item breakID="148" restoreID="94951" /> <!-- Sword of Valhalla -->
			<item breakID="7889" restoreID="93432" /> <!-- Wizard's Tear -->
			<!-- Duplication for sealed items -->
			<item breakID="94951" /> <!-- Sword of Valhalla -->
			<item breakID="93432" /> <!-- Wizard's Tear -->
			<!-- One-handed Blunts -->
			<item breakID="91" restoreID="94925" /> <!-- Heavy War Axe -->
			<item breakID="171" restoreID="93424" /> <!-- Deadman's Glory -->
			<item breakID="175" restoreID="93425" /> <!-- Art of Battle Axe -->
			<item breakID="95434" restoreID="95448" /> <!-- Giants' Club -->
			<item breakID="96720" restoreID="96722" /> <!-- Giant's One-handed Axe -->
			<!-- Duplication for sealed items -->
			<item breakID="94925" /> <!-- Heavy War Axe -->
			<item breakID="93424" /> <!-- Deadman's Glory -->
			<item breakID="93425" /> <!-- Art of Battle Axe -->
			<item breakID="95448" /> <!-- Giants' Club -->
			<item breakID="96722" /> <!-- Giant's One-handed Axe -->
			<!-- One-handed Sword -->
			<item breakID="79" restoreID="93422" /> <!-- Damascus Sword -->
			<item breakID="142" restoreID="94947" /> <!-- Keshanberk -->
			<item breakID="95442" restoreID="95456" /> <!-- Berserker's Sword -->
			<item breakID="96815" /> <!-- Ancient Weapon - B-grade (Time-limited) Sealed -->
			<!-- Duplication for sealed items -->
			<item breakID="93422" /> <!-- Damascus Sword -->
			<item breakID="94947" /> <!-- Keshanberk -->
			<item breakID="95456" /> <!-- Berserker's Sword -->
			<!-- One-handed Staffs -->
			<item breakID="7892" restoreID="95306" /> <!-- Spell Breaker -->
			<item breakID="7893" restoreID="95307" /> <!-- Kaim Vanul's Bones -->
			<item breakID="95432" restoreID="95446" /> <!-- Excuro's Staff -->
			<!-- Duplication for sealed items -->
			<item breakID="95306" /> <!-- Spell Breaker -->
			<item breakID="95307" /> <!-- Kaim Vanul's Bones -->
			<item breakID="95446" /> <!-- Excuro's Staff -->
			<!-- Dual Swords -->
			<item breakID="2600" restoreID="95270" /> <!-- Raid Sword*Caliburs -->
			<item breakID="2613" restoreID="95283" /> <!-- Ultimate Sword*Sword of Delusion -->
			<item breakID="2586" restoreID="95256" /> <!-- Katana*Ultimate Sword -->
			<item breakID="2598" restoreID="95268" /> <!-- Spirit Sword*Samurai Long Sword -->
			<item breakID="2568" restoreID="95239" /> <!-- Stormbringer*Sword of Delusion -->
			<item breakID="2625" restoreID="95295" /> <!-- Tsurugi*Samurai Long Sword -->
			<item breakID="2619" restoreID="95289" /> <!-- Sword of Delusion*Tsurugi -->
			<item breakID="2566" restoreID="95237" /> <!-- Stormbringer*Caliburs -->
			<item breakID="2615" restoreID="95285" /> <!-- Ultimate Sword*Tsurugi -->
